---
# Default kubo-deployment deploys a (mostly) HA configuration.
# Use this override to only deploy single instance of each job,
# in a single Availability Zone.
- type: replace
  path: /instance_groups/name=master/instances
  value: 3
- type: replace
  path: /instance_groups/name=worker/instances
  value: 3

- type: replace
  path: /instance_groups/name=master/azs
  value: [ us-east1-b ]
- type: replace
  path: /instance_groups/name=worker/azs
  value: [ us-east1-b ]
